server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/d/api/employee/**
        filters:
        - RewritePath=/d/api/employee/?(?<segment>.*), /$\{segment}
        - EmployeeFilter
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/d/api/consumer/**
        filters:
        - RewritePath=/d/api/employee/?(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug
