server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
      - name: LoggerFilter
        args:
          order: -1
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/d/api/employee/**
        filters:
        - RewritePath=/d/api/employee/?(?<segment>.*), /$\{segment}
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
        - Path=/d/api/consumer/{segment}
        filters:
        - SetPath=/{segment}

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: debug
